DEBUG 2021-03-18 16:22:59 __init__.py: 241] CACHEDIR=/home/bao/.cache/matplotlib
DEBUG 2021-03-18 16:22:59 font_manager.py: 1436] Using fontManager instance from /home/bao/.cache/matplotlib/fontlist-v330.json
DEBUG 2021-03-18 16:22:59 selector_events.py: 59] Using selector: EpollSelector
INFO 2021-03-18 16:22:59 FaceDetModelLoader.py: 16] Start to analyze the face detection model, model path: face_sdk/models, model category: face_detection，model name: face_detection_1.0
INFO 2021-03-18 16:22:59 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2021-03-18 16:22:59 FaceDetModelLoader.py: 32] The model failed to load, please check the model path: face_sdk/models/face_detection/face_detection_1.0/face_detection_retina.pkl!
INFO 2021-03-18 16:22:59 FaceDetModelLoader.py: 16] Start to analyze the face detection model, model path: face_sdk/models, model category: face_detection，model name: face_detection_1.0
INFO 2021-03-18 16:22:59 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2021-03-18 16:22:59 FaceDetModelLoader.py: 32] The model failed to load, please check the model path: face_sdk/models/face_detection/face_detection_1.0/face_detection_retina.pkl!
INFO 2021-03-18 16:22:59 FaceDetModelLoader.py: 16] Start to analyze the face detection model, model path: face_sdk/models, model category: face_detection，model name: face_detection_1.0
INFO 2021-03-18 16:22:59 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2021-03-18 16:22:59 FaceDetModelLoader.py: 16] Start to analyze the face detection model, model path: face_sdk/models, model category: face_detection，model name: face_detection_1.0
INFO 2021-03-18 16:22:59 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2021-03-18 16:22:59 FaceDetModelLoader.py: 32] The model failed to load, please check the model path: face_sdk/models/face_detection/face_detection_1.0/face_detection_retina.pkl!
INFO 2021-03-18 16:22:59 FaceDetModelLoader.py: 16] Start to analyze the face detection model, model path: face_sdk/models, model category: face_detection，model name: face_detection_1.0
ERROR 2021-03-18 16:22:59 FaceDetModelLoader.py: 32] The model failed to load, please check the model path: face_sdk/models/face_detection/face_detection_1.0/face_detection_retina.pkl!
INFO 2021-03-18 16:22:59 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
INFO 2021-03-18 16:22:59 FaceDetModelLoader.py: 16] Start to analyze the face detection model, model path: face_sdk/models, model category: face_detection，model name: face_detection_1.0
INFO 2021-03-18 16:22:59 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2021-03-18 16:22:59 FaceDetModelLoader.py: 32] The model failed to load, please check the model path: face_sdk/models/face_detection/face_detection_1.0/face_detection_retina.pkl!
ERROR 2021-03-18 16:22:59 FaceDetModelLoader.py: 32] The model failed to load, please check the model path: face_sdk/models/face_detection/face_detection_1.0/face_detection_retina.pkl!
INFO 2021-03-18 16:22:59 FaceDetModelLoader.py: 16] Start to analyze the face detection model, model path: face_sdk/models, model category: face_detection，model name: face_detection_1.0
INFO 2021-03-18 16:22:59 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2021-03-18 16:22:59 FaceDetModelLoader.py: 32] The model failed to load, please check the model path: face_sdk/models/face_detection/face_detection_1.0/face_detection_retina.pkl!
INFO 2021-03-18 16:22:59 FaceDetModelLoader.py: 16] Start to analyze the face detection model, model path: face_sdk/models, model category: face_detection，model name: face_detection_1.0
INFO 2021-03-18 16:22:59 BaseModelLoader.py: 34] Successfully parsed the model configuration file meta.json!
ERROR 2021-03-18 16:22:59 FaceDetModelLoader.py: 32] The model failed to load, please check the model path: face_sdk/models/face_detection/face_detection_1.0/face_detection_retina.pkl!
DEBUG 2021-03-18 16:23:47 __init__.py: 241] (private) matplotlib data path: /home/bao/anaconda3/envs/my_env/lib/python3.9/site-packages/matplotlib/mpl-data
DEBUG 2021-03-18 16:23:47 __init__.py: 241] matplotlib data path: /home/bao/anaconda3/envs/my_env/lib/python3.9/site-packages/matplotlib/mpl-data
DEBUG 2021-03-18 16:23:47 __init__.py: 241] CONFIGDIR=/home/bao/.config/matplotlib
DEBUG 2021-03-18 16:23:47 __init__.py: 1480] matplotlib version 3.3.4
DEBUG 2021-03-18 16:23:47 __init__.py: 1481] interactive is False
DEBUG 2021-03-18 16:23:47 __init__.py: 1482] platform is linux
